language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
script:
  - flake8
  - coverage run --source=. -m unittest discover
deploy:
  provider: script
  script: curl -X POST $DOCKERHUB_TRIGGER_URL
  on:
    all_branches: true
after_success:
  - coveralls

  